# Generated by Django 4.1.7 on 2023-04-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PathFinderApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
        migrations.CreateModel(
            name="UserChatPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=1000)),
                ("query_response", models.CharField(max_length=1000)),
                ("query_date", models.DateField()),
                ("query_time", models.TimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PathFinderApp.user",
                    ),
                ),
            ],
        ),
    ]
