# Generated by Django 4.1.7 on 2023-04-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PathFinderApp", "0003_remove_userchatprompt_query_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchatprompt",
            name="query_response",
        ),
    ]
