# Generated by Django 4.1.7 on 2023-04-27 21:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PathFinderApp", "0004_remove_userchatprompt_query_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50, verbose_name=django.contrib.auth.models.User
            ),
        ),
    ]
