# Generated by Django 4.1.7 on 2023-05-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PathFinderApp", "0005_alter_user_username"),
        ("PathFinderApp", "0005_notes"),
    ]

    operations = []
