# Generated by Django 4.2 on 2023-05-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PathFinderApp', '0005_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='set_password',
        ),
    ]
