# Generated by Django 4.1.7 on 2023-05-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PathFinderApp', '0006_merge_0005_alter_user_username_0005_notes'),
        ('PathFinderApp', '0007_rename_set_password_user_user_password_profile_meep'),
    ]

    operations = [
    ]
