# https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-gitlab/
image: 
  name: docker/compose:1.29.2
  entrypoint: [""]

stages:
  - test
  - deploy

test_stage:
  stage: test
  tags:
    - docker
  script:
    - echo "test"
deploy_stage:
  stage: deploy
  tags:
    - docker
  script:
    - ./deploy.sh