version: '3.8'

services:
  pathfinderapp:
    build:
      context: .
      dockerfile: Dockerfile
      # cache_from:
      #   - "${WEB_IMAGE}"
    # image: "${WEB_IMAGE}"
    command: python manage.py runserver
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - .:/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - pathfinderapp
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      # cache_from:
      #   - "${NGINX_IMAGE}"
  patjfinderdb:
    image: postgres:14.7
    environment:
      - SECRET_KEY=SuperSecretDevKey
      - DEBUG=1
      - DB_HOST=pathfinderdb
      - DB_NAME=devdb
      - DB_USER=postgres
      - DB_PASSWORD=SuperSecretDevPassword
    ports:
      - 0.0.0.0:5432:5432

volumes:
  static_volume:
  media_volume:
  # pathfinderdb:
  #   image: postgres:14.0-alpine
  #   environment:
  #     - POSTGRES_DB=pathfinderdb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=SuperSecretDevPassword