version: '3.8'

services:
  pathfinderapp:
    build:
      context: .
      dockerfile: Dockerfile
      # cache_from:
      #   - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: python manage.py runserver
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - .:/app
  patjfinderdb:
    image: postgres:14.7
    environment:
      - SECRET_KEY=SuperSecretDevKey
      - DEBUG=1
      - DB_HOST=pathfinderdb
      - DB_NAME=devdb
      - DB_USER=postgres
      - DB_PASSWORD=SuperSecretDevPassword
    ports:
      - 127.0.0.1:5432:5432

  # pathfinderdb:
  #   image: postgres:14.0-alpine
  #   environment:
  #     - POSTGRES_DB=pathfinderdb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=SuperSecretDevPassword