version: '3.8'

services:
  pathfinderapp:
    container_name: pathfinderapp
    build:
      context: .
      dockerfile: Dockerfile
      # cache_from:
      #   - "${WEB_IMAGE}"
    # image: "${WEB_IMAGE}"
    command: gunicorn PathFinder.PathFinderBase.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/pathfinderapp
      - static_volume:/root/teamdai58-22/PathFinder/static
      #- media_volume:/PathFinder/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.staging
    expose:
      - "8000"
    depends_on:
      - pathfinderdb
 

  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    build:
      context: .
      dockerfile: ./nginx/Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/:/etc/nginx
      - /root/teamdai58-22.bham.team:/etc/ssl/private
      - static_volume:/root/teamdai58-22/PathFinder/static
      #- certs:/root/teamdai58-22.bham.team/
      #- html:/usr/share/nginx/html
      #- vhost:/etc/nginx/vhost.d
      #- /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - pathfinderapp
      #- media_volume:/app/media
      # cache_from:
      #   - "${NGINX_IMAGE}"

  #web-api:
    #container_name: web-api
    #depends_on:
      #- nginx-proxy
    #build:
      #context: .
    #ports:
      #- "5000:5000"
    #restart: always

  pathfinderdb:
    container_name: pathfinderdb
    image: postgres:14.7
    volumes:
      - pathfinderdb_data:/var/lib/postgresql/data
    environment:
      - SECRET_KEY=SuperSecretDevKey
      #- DEBUG=1
      #- DB_HOST=localhost
      - DB_NAME=pathfinderdb
      - DB_USER=pathfinderdbsu
      - DB_PASSWORD=pa$$wordFinder
    ports:
      - 0.0.0.0:5432:5432
volumes:
  pathfinderdb_data:
  static_volume:
  certs:
  html:
  vhost:
  acme:

  # pathfinderdb:
  #   image: postgres:14.0-alpine
  #   environment:
  #     - POSTGRES_DB=pathfinderdb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=SuperSecretDevPassword
